//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funlam_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbfunlamEntities : DbContext
    {
        public dbfunlamEntities()
            : base("name=dbfunlamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<claseestilo> claseestilos { get; set; }
        public virtual DbSet<curso> cursos { get; set; }
        public virtual DbSet<descuento> descuentos { get; set; }
        public virtual DbSet<detalle_persona_curso> detalle_persona_curso { get; set; }
        public virtual DbSet<detalles_usuario> detalles_usuario { get; set; }
        public virtual DbSet<deuda> deudas { get; set; }
        public virtual DbSet<liquidacione> liquidaciones { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<modulo> modulos { get; set; }
        public virtual DbSet<plan_financiacion> plan_financiacion { get; set; }
        public virtual DbSet<programa> programas { get; set; }
        public virtual DbSet<recaudo> recaudoes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<saldos_favor> saldos_favor { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<calendario> calendarios { get; set; }
        public virtual DbSet<evento> eventos { get; set; }
    }
}
