//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funlam_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recaudo
    {
        public int id_recaudos { get; set; }
        public System.DateTime fecha_recaudo { get; set; }
        public decimal valor { get; set; }
        public string tipo { get; set; }
        public string estado { get; set; }
        public string financiacion { get; set; }
        public string descripcion { get; set; }
        public int id_usuario { get; set; }
        public int id_liquidacion { get; set; }
    
        public virtual liquidacione liquidacione { get; set; }
    }
}
